In [1]:
import os; os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import tensorflow as tf
from tensorflow import keras

In [2]:
classifier = keras.models.load_model("models/classifier", compile=True)
ellipse = keras.models.load_model("models/ellipse_regressor", compile=True)
rectangle = keras.models.load_model("models/rectangle_regressor", compile=True)
triangle = keras.models.load_model("models/triangle_regressor", compile=True)
classifier._name="classifier"
ellipse._name="ellipse"
rectangle._name="rectangle"
triangle._name="triangle"

In [3]:
def make_wizard():
    inputs = keras.Input(shape=(70, 70, 1))
    shape = tf.argmax(tf.gather(classifier(inputs), 0))
    outputs = tf.tuple([shape - 1, ellipse(inputs), rectangle(inputs), triangle(inputs)])
    return keras.Model(inputs=inputs, outputs=outputs, name="ShapeWizard")

In [4]:
wizard = make_wizard()

In [5]:
wizard(tf.ones((1, 70, 70, 1)))

[<tf.Tensor: shape=(), dtype=int64, numpy=-1>,
 <tf.Tensor: shape=(1, 8), dtype=float32, numpy=
 array([[0.24543212, 0.6442481 , 0.32226545, 0.215644  , 0.7408611 ,
         0.34888875, 0.7016524 , 0.8112767 ]], dtype=float32)>,
 <tf.Tensor: shape=(1, 8), dtype=float32, numpy=
 array([[0.24047792, 0.8734088 , 0.10136943, 0.29787955, 0.7557267 ,
         0.13280201, 0.895409  , 0.7083211 ]], dtype=float32)>,
 <tf.Tensor: shape=(1, 6), dtype=float32, numpy=
 array([[0.38967794, 0.94285154, 0.13885719, 0.13914545, 0.8961349 ,
         0.35414615]], dtype=float32)>]

In [9]:
wizard.save("models/ShapeWizard", save_format="h5")